
version: '3.8'

services:
  web:
    build: .
    container_name: erp_web
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html/
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: erp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp
      MYSQL_USER: erpuser
      MYSQL_PASSWORD: senha123
      TZ: America/Sao_Paulo
    command: --default-time-zone='-03:00'
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: erp_phpmyadminS
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  dbdata:
